### ISSUE TITLE
Invisible cursor and too big GUI

### ISSUE THREAD

**Issue by DarkSny** [tonihele/OpenKeeper#411] opened 2022-05-15 18:39 UTC
The game runs but I cannot see the mouse cursor and the GUI is too big so it is unplayable. Is there a way to fix this issue?
I'm using Windows 7.
Thanks.

**Comment by tonihele** [comment] 2022-05-16 05:32
Hi,

could you please provide a screenshot of the issue and some specs from your computer and Java version.

**Comment by ArchDemons** [comment] 2022-05-16 13:25
You can change window resolution in main menu settings

**Comment by DarkSny** [comment] 2022-05-16 13:39
I tried that but it does not work. It does nothing when I try to change the resolution in the settings.

**Comment by tonihele** [comment] 2022-05-16 14:29
Looks like the log is missing some important parts. The LWJGL initialization.

We do have this setting (openkeeper.properties in <youruserfolder>/.OpenKeeper):
`UseCursors(bool)=false`

This will disable the hardware cursor and just use the system one.

Can you also show the resolution settings you are getting? A screen shot with the drop down should be sufficient. And you did click the V-button to apply the changes?

**Comment by DarkSny** [comment] 2022-05-16 15:01
I tried putting the UseCursors(bool)=false in the openkeeper.properties as you suggested but nothing changes. Still invisible cursor. 
Yep I did click the V-button on bottom right corner to apply the changes but nothing happens. I also tried changing from fullscreen to windowed but nothing. It's like the settings do not work at all. The game is stuck in 640x480. When trying to change anything in the settings and applying it with the V-button, it does nothing and when I restart the game it just goes back to how it was before. Nothing changes. Here's screenshot of in-game settings that the game is stuck on.

![dkok2](https://user-images.githubusercontent.com/13250755/168622756-ce45602a-9481-49b0-aeea-07f0beb9d692.PNG)

![dkok3](https://user-images.githubusercontent.com/13250755/168622784-e74735d7-a376-40f4-b251-7d7e8d483e45.PNG)

![dkok4](https://user-images.githubusercontent.com/13250755/168622811-40bac075-da7a-4715-9093-4bf91550f511.PNG)

**Comment by tonihele** [comment] 2022-05-16 15:06
How about if you change the resolution? It should be in the same config file as the UseCursors. Just make sure you find the correct openkeeper.properties. In your user folder, NOT the one in the run/app folder.

**Comment by DarkSny** [comment] 2022-05-16 15:34
Thank you so much! It works now! I was in the wrong openkeeper.properties. Also I would like to ask, the game lags a bit, is there a way to change the texture, model detail or something that will make it run smooth?

**Comment by tonihele** [comment] 2022-05-16 20:33
I'm closing this. Unfortunately nothing was fixed and there is probably some issue somewhere. But I just can't reproduce it with anything. Lets hope it sorts itself out at some stage of development. Feel free to add any details here or better yet, debug, fix it and submit a PR :)

**Closed by tonihele** 2022-05-16 20:33 UTC
